[package]
name = "git_push"
version = "0.1.0"
authors = ["Ynit <393227384@qq.com>"]
edition = "2018"


[dependencies]
ssh2 = "0.8"
git2 = { version = "0.13", default-features = false }
libssh2-sys = "0.2"
structopt = "0.3"
directories = "3.0"